artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://prod-dcd-datasets-cache-zipfiles.s3.eu-west-1.amazonaws.com/cp3473x7xv-3.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_transformation: 
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/LG 18650HG2 Li-ion Battery Data and Example Deep Neural Network xEV SOC Estimator Script\LG_HG2_Original_Dataset_McMasterUniversity_Jan_2020
  train_names: ['\0degC\589_LA92']
  test_names: ['\0degC\589_Mixed1']
  downsampling: True
  output_capacity: False 
  scale_test: False 
  output_time: False
  steps: 30 







